POST http://localhost:3000/add/product
Content-Type: application/json

{
    "productName": "Apple ipad -2 s",
    "productPrice": 150
}

###

POST http://localhost:3000/updateProduct
Content-Type: application/json

{
    "productToUpdate": "Samsung 2",
    "productName": "Samsung Grand neo 2021'"
}

###

GET http://localhost:3000/products

